# Generated by Django 3.2.15 on 2022-09-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='suitable_for',
            field=models.CharField(max_length=80),
        ),
    ]
