# Generated by Django 3.2.15 on 2022-09-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0002_auto_20220906_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dish_name',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='name',
        ),
    ]
