# Generated by Django 3.2.15 on 2022-09-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0003_auto_20220911_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='user_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='dish_name',
            new_name='dish_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
