# Generated by Django 3.2.15 on 2022-09-17 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meal_planner', '0004_auto_20220912_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='recipe_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
