# Generated by Django 3.2.15 on 2022-09-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0005_alter_recipe_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
